<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="1.154" tests="1" failures="2">
  <testsuite name="" timestamp="2023-06-27T15:15:22" tests="0" file="cypress/e2e/block-basics.cy.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Root Suite.Blocks Tests" timestamp="2023-06-27T15:15:22" tests="1" time="1.127" failures="2">
    <testcase name="&quot;before each&quot; hook: setupBeforeEach for &quot;Add Block: Empty&quot;" time="0.000" classname="Blocks Tests">
      <failure message="`cy.request()` failed on:

http://localhost:8080/Plone/

The response we received from your web server was:

  &gt; 403: Forbidden

This was considered a failure because the status code was not `2xx` or `3xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: http://localhost:8080/Plone/
Headers: {
  &quot;Connection&quot;: &quot;keep-alive&quot;,
  &quot;user-agent&quot;: &quot;Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/11.1.0 Chrome/106.0.5249.51 Electron/21.0.0 Safari/537.36&quot;,
  &quot;accept&quot;: &quot;application/json&quot;,
  &quot;cookie&quot;: &quot;auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY4NzkyMjEyMiwiZnVsbG5hbWUiOm51bGx9.V6SbUKQQBZa3bU3-yPPe8KpGSK_nwta3oOYDS23zzU0; __ac=NjE2NDZkNjk2ZTo2MTY0NmQ2OTZl&quot;,
  &quot;authorization&quot;: &quot;Basic YWRtaW46YWRtaW4=&quot;,
  &quot;accept-encoding&quot;: &quot;gzip, deflate&quot;,
  &quot;content-type&quot;: &quot;application/json&quot;,
  &quot;content-length&quot;: 306
}
Body: {&quot;@type&quot;:&quot;Folder&quot;,&quot;id&quot;:&quot;cypress&quot;,&quot;title&quot;:&quot;Cypress&quot;,&quot;blocks&quot;:{&quot;d3f1c443-583f-4e8e-a682-3bf25752a300&quot;:{&quot;@type&quot;:&quot;title&quot;},&quot;7624cf59-05d0-4055-8f55-5fd6597d84b0&quot;:{&quot;@type&quot;:&quot;text&quot;}},&quot;blocks_layout&quot;:{&quot;items&quot;:[&quot;d3f1c443-583f-4e8e-a682-3bf25752a300&quot;,&quot;7624cf59-05d0-4055-8f55-5fd6597d84b0&quot;]},&quot;allow_discussion&quot;:false}

-----------------------------------------------------------

The response we got was:

Status: 403 - Forbidden
Headers: {
  &quot;content-length&quot;: &quot;97&quot;,
  &quot;content-type&quot;: &quot;application/json&quot;,
  &quot;date&quot;: &quot;Tue, 27 Jun 2023 15:15:22 GMT&quot;,
  &quot;server&quot;: &quot;waitress&quot;,
  &quot;via&quot;: &quot;waitress&quot;,
  &quot;x-frame-options&quot;: &quot;SAMEORIGIN&quot;,
  &quot;x-powered-by&quot;: &quot;Zope (www.zope.dev), Python (www.python.org)&quot;
}
Body: {
  &quot;error&quot;: {
    &quot;message&quot;: &quot;Disallowed subobject type: Folder&quot;,
    &quot;type&quot;: &quot;Forbidden&quot;
  }
}


https://on.cypress.io/request

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Blocks Tests`" type="CypressError"><![CDATA[CypressError: `cy.request()` failed on:

http://localhost:8080/Plone/

The response we received from your web server was:

  > 403: Forbidden

This was considered a failure because the status code was not `2xx` or `3xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: http://localhost:8080/Plone/
Headers: {
  "Connection": "keep-alive",
  "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/11.1.0 Chrome/106.0.5249.51 Electron/21.0.0 Safari/537.36",
  "accept": "application/json",
  "cookie": "auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY4NzkyMjEyMiwiZnVsbG5hbWUiOm51bGx9.V6SbUKQQBZa3bU3-yPPe8KpGSK_nwta3oOYDS23zzU0; __ac=NjE2NDZkNjk2ZTo2MTY0NmQ2OTZl",
  "authorization": "Basic YWRtaW46YWRtaW4=",
  "accept-encoding": "gzip, deflate",
  "content-type": "application/json",
  "content-length": 306
}
Body: {"@type":"Folder","id":"cypress","title":"Cypress","blocks":{"d3f1c443-583f-4e8e-a682-3bf25752a300":{"@type":"title"},"7624cf59-05d0-4055-8f55-5fd6597d84b0":{"@type":"text"}},"blocks_layout":{"items":["d3f1c443-583f-4e8e-a682-3bf25752a300","7624cf59-05d0-4055-8f55-5fd6597d84b0"]},"allow_discussion":false}

-----------------------------------------------------------

The response we got was:

Status: 403 - Forbidden
Headers: {
  "content-length": "97",
  "content-type": "application/json",
  "date": "Tue, 27 Jun 2023 15:15:22 GMT",
  "server": "waitress",
  "via": "waitress",
  "x-frame-options": "SAMEORIGIN",
  "x-powered-by": "Zope (www.zope.dev), Python (www.python.org)"
}
Body: {
  "error": {
    "message": "Disallowed subobject type: Folder",
    "type": "Forbidden"
  }
}


https://on.cypress.io/request

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Blocks Tests`
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:144236:80)
    at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:11327:23)
    at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:9262:31)
    at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:9319:18)
    at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:9364:10)
    at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:9444:18)
    at _drainQueueStep (http://localhost:3000/__cypress/runner/cypress_runner.js:6034:12)
    at _drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:6027:9)
    at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:6043:5)
    at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:5913:14)
From Your Spec Code:
    at Context.eval (webpack:///./cypress/support/commands.js:82:9)]]></failure>
    </testcase>
    <testcase name="&quot;after each&quot; hook: tearDownAfterEach for &quot;Add Block: Empty&quot;" time="0.000" classname="Blocks Tests">
      <failure message="`cy.request()` failed on:

http://localhost:8080/Plone/cypress

The response we received from your web server was:

  &gt; 404: Not Found

This was considered a failure because the status code was not `2xx` or `3xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

-----------------------------------------------------------

The request we sent was:

Method: DELETE
URL: http://localhost:8080/Plone/cypress
Headers: {
  &quot;Connection&quot;: &quot;keep-alive&quot;,
  &quot;user-agent&quot;: &quot;Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/11.1.0 Chrome/106.0.5249.51 Electron/21.0.0 Safari/537.36&quot;,
  &quot;accept&quot;: &quot;application/json&quot;,
  &quot;cookie&quot;: &quot;auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY4NzkyMjEyMywiZnVsbG5hbWUiOm51bGx9.MViWuEtOiJokN_uT4iZ7JiicHnzSCkcEOEgGPYFNAoA; __ac=NjE2NDZkNjk2ZTo2MTY0NmQ2OTZl&quot;,
  &quot;authorization&quot;: &quot;Basic YWRtaW46YWRtaW4=&quot;,
  &quot;accept-encoding&quot;: &quot;gzip, deflate&quot;,
  &quot;content-type&quot;: &quot;application/json&quot;,
  &quot;content-length&quot;: 2
}
Body: {}

-----------------------------------------------------------

The response we got was:

Status: 404 - Not Found
Headers: {
  &quot;content-length&quot;: &quot;96&quot;,
  &quot;content-type&quot;: &quot;application/json&quot;,
  &quot;date&quot;: &quot;Tue, 27 Jun 2023 15:15:23 GMT&quot;,
  &quot;server&quot;: &quot;waitress&quot;,
  &quot;via&quot;: &quot;waitress&quot;,
  &quot;x-powered-by&quot;: &quot;Zope (www.zope.dev), Python (www.python.org)&quot;
}
Body: {
  &quot;message&quot;: &quot;Resource not found: http://localhost:8080/Plone/cypress&quot;,
  &quot;type&quot;: &quot;NotFound&quot;
}


https://on.cypress.io/request

Because this error occurred during a `after each` hook we are skipping the remaining tests in the current suite: `Blocks Tests`" type="CypressError"><![CDATA[CypressError: `cy.request()` failed on:

http://localhost:8080/Plone/cypress

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx` or `3xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

-----------------------------------------------------------

The request we sent was:

Method: DELETE
URL: http://localhost:8080/Plone/cypress
Headers: {
  "Connection": "keep-alive",
  "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/11.1.0 Chrome/106.0.5249.51 Electron/21.0.0 Safari/537.36",
  "accept": "application/json",
  "cookie": "auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY4NzkyMjEyMywiZnVsbG5hbWUiOm51bGx9.MViWuEtOiJokN_uT4iZ7JiicHnzSCkcEOEgGPYFNAoA; __ac=NjE2NDZkNjk2ZTo2MTY0NmQ2OTZl",
  "authorization": "Basic YWRtaW46YWRtaW4=",
  "accept-encoding": "gzip, deflate",
  "content-type": "application/json",
  "content-length": 2
}
Body: {}

-----------------------------------------------------------

The response we got was:

Status: 404 - Not Found
Headers: {
  "content-length": "96",
  "content-type": "application/json",
  "date": "Tue, 27 Jun 2023 15:15:23 GMT",
  "server": "waitress",
  "via": "waitress",
  "x-powered-by": "Zope (www.zope.dev), Python (www.python.org)"
}
Body: {
  "message": "Resource not found: http://localhost:8080/Plone/cypress",
  "type": "NotFound"
}


https://on.cypress.io/request

Because this error occurred during a `after each` hook we are skipping the remaining tests in the current suite: `Blocks Tests`
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:144236:80)
    at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:11327:23)
    at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:9262:31)
    at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:9319:18)
    at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:9364:10)
    at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:9444:18)
    at _drainQueueStep (http://localhost:3000/__cypress/runner/cypress_runner.js:6034:12)
    at _drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:6027:9)
    at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:6043:5)
    at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:5913:14)
From Your Spec Code:
    at Context.eval (webpack:///./cypress/support/commands.js:137:5)]]></failure>
    </testcase>
  </testsuite>
</testsuites>